export const portalCopy = {
  welcome: {
    greeting: (name: string) => `Ciao, ${name}.`,
    subtitle: "Siamo contentissimi che hai scelto Liquid.",
    body: "Da qui partiamo davvero: tra poco avrai un sito su misura, e questo link è la tua cabina di pilotaggio.",
    cta: "Iniziamo",
    footnote: "Il primo passo richiede pochi minuti — poi ci pensiamo noi.",
    overview: [
      {
        title: "Due minuti di partenza",
        description: "Acconto e dati fattura. Poi si entra nel vivo.",
        accent: "coral" as const,
        icon: "rocket" as const,
      },
      {
        title: "Scegliamo lo stile",
        description: "Like e ispirazioni visive per capire il tuo gusto.",
        accent: "mint" as const,
        icon: "palette" as const,
      },
      {
        title: "Costruiamo il sito",
        description: "Tu carichi, noi sviluppiamo, tu approvi.",
        accent: "indigo" as const,
        icon: "sparkles" as const,
      },
    ],
  },
  maintenance: {
    summary: "Da qui puoi chiederci aggiornamenti quando ne hai bisogno.",
  },
  gatedDeposit: "Prima sblocchiamo l'acconto e i dati di fatturazione — poi si passa alla parte creativa.",
  onboarding: {
    depositLabel: "Acconto per iniziare",
    amountPending: "Importo in arrivo da Liquid",
    bankDetails: "Coordinate bancarie",
    markPaidHint: "Effettua il bonifico, poi premi il bottone — ci metti un minuto.",
    markPaidCta: "Ho fatto il bonifico",
    markPaidPending: "Un attimo…",
    paidConfirmed: "Acconto confermato",
    paidConfirmedHint: "Perfetto, puoi procedere.",
    markedPaid: "Bonifico segnalato",
    markedPaidHint: "Lo verifichiamo a breve. Nel frattempo completa i dati di fatturazione.",
    invoiceTitle: "I tuoi dati di fatturazione",
    invoiceHint: "Servono per la fattura. Si salvano da soli mentre scrivi.",
    invoiceComplete: "Vai alla scelta dello stile",
    invoiceCompletePending: "Preparo il prossimo step…",
  },
  style: {
    howItWorksTitle: "Come funziona",
    howItWorks: "Apri i siti qui sotto e metti like a ciò che ti ispira. Non esiste una scelta sbagliata — stiamo capendo il tuo gusto.",
    confirmTitle: "Pronto per continuare?",
    confirmHeading: "Ho scelto il mio stile",
    confirmCta: "Perfetto, andiamo avanti",
    noReferences: "I riferimenti visivi appariranno qui appena li aggiungiamo.",
    addInspiration: "Aggiungi un sito di ispirazione",
    addInspirationHint: "Hai altri riferimenti?",
  },
  waiting: {
    title: "Il tuo sito sta prendendo forma.",
    body: "Ci stiamo lavorando adesso. Ti scriviamo appena c'è qualcosa da vedere.",
  },
  delivery: {
    eyebrow: "Ci siamo quasi",
    title: "Ultimi passi prima di andare online",
    body: "Grazie per il lavoro fatto insieme. Manca solo il saldo — poi pubblichiamo.",
    hint: "Completa il saldo finale per sbloccare la pubblicazione.",
    onlinePending: "Abbiamo ricevuto la conferma: mettiamo online il sito al più presto e ti scriviamo appena sarà visibile.",
  },
  toasts: {
    uploadSuccess: "Perfetto, ricevuto!",
    uploadError: "Caricamento non riuscito. Riprova o usa un file più piccolo (max 100 MB).",
    revisionSent: "Feedback inviato — lo prendiamo subito.",
    approvalSent: "Feedback inviato — lo vediamo prima della pubblicazione.",
    paymentConfirmed: "Pagamento segnato come completato.",
    maintenanceSent: "Richiesta inviata — ci pensiamo noi.",
  },
} as const;
