/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as ApiPublicCaptureKindIdRouteImport } from './routes/api/public/capture.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaptureKindIdRoute = ApiPublicCaptureKindIdRouteImport.update({
  id: '/api/public/capture/$kind/$id',
  path: '/api/public/capture/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b/$slug': typeof BSlugRoute
  '/api/public/capture/$kind/$id': typeof ApiPublicCaptureKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b/$slug': typeof BSlugRoute
  '/api/public/capture/$kind/$id': typeof ApiPublicCaptureKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b/$slug': typeof BSlugRoute
  '/api/public/capture/$kind/$id': typeof ApiPublicCaptureKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/b/$slug' | '/api/public/capture/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/b/$slug' | '/api/public/capture/$kind/$id'
  id: '__root__' | '/' | '/b/$slug' | '/api/public/capture/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BSlugRoute: typeof BSlugRoute
  ApiPublicCaptureKindIdRoute: typeof ApiPublicCaptureKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/capture/$kind/$id': {
      id: '/api/public/capture/$kind/$id'
      path: '/api/public/capture/$kind/$id'
      fullPath: '/api/public/capture/$kind/$id'
      preLoaderRoute: typeof ApiPublicCaptureKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BSlugRoute: BSlugRoute,
  ApiPublicCaptureKindIdRoute: ApiPublicCaptureKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
